################################################################################
# Judge0 Configuration File
################################################################################
# Judge0 is a robust and scalable open-source online code execution system.
# You can find more about Judge0 on https://judge0.com and https://github.com/judge0/judge0.

# PostgreSQL
POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0password

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0password

# Judge0
## General
JUDGE0_VERSION=1.13.0
JUDGE0_HOMEPAGE=https://judge0.com

## Maintenance
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true

## Security
ALLOW_ENABLE_NETWORK=false
ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=false

## Limits
MAX_QUEUE_SIZE=100
MAX_CPU_TIME_LIMIT=15
MAX_CPU_EXTRA_TIME=5
MAX_WALL_TIME_LIMIT=20
MAX_MEMORY_LIMIT=512000
MAX_STACK_LIMIT=128000
MAX_PROCESSES_AND_OR_THREADS=60
MAX_FILE_SIZE=1024

## Timeouts
SUBMISSION_CACHE_DURATION=1h
